graph LR
  AppModule --> ConfigModule
  ConfigModule --> ConfigHostModule
  ConfigHostModule --> ConfigModule
  ConfigHostModule --> DatabaseService
  DatabaseService --> ConfigModule
  DatabaseService --> ConfigHostModule
  ConfigModule --> DatabaseService
  AppModule --> DatabaseService
  AppModule --> AuthModule
  AuthModule --> JwtModule
  JwtModule --> ConfigModule
  JwtModule --> ConfigHostModule
  JwtModule --> DatabaseService
  AuthModule --> DatabaseService
  AuthModule --> RolesModule
  RolesModule --> DatabaseService
  RolesModule --> ConfigModule
  RolesModule --> ConfigHostModule
  AuthModule --> PermissionsModule
  PermissionsModule --> DatabaseService
  PermissionsModule --> ConfigModule
  PermissionsModule --> ConfigHostModule
  AuthModule --> MailModule
  MailModule --> ConfigModule
  MailModule --> ConfigHostModule
  MailModule --> DatabaseService
  AuthModule --> SmsModule
  SmsModule --> ConfigModule
  SmsModule --> ConfigHostModule
  SmsModule --> DatabaseService
  AuthModule --> ConfigModule
  AuthModule --> ConfigHostModule
  AppModule --> RolesModule
  AppModule --> UsersModule
  UsersModule --> ConfigModule
  UsersModule --> ConfigHostModule
  UsersModule --> DatabaseService
  AppModule --> TestingModule
  TestingModule --> ConfigModule
  TestingModule --> ConfigHostModule
  TestingModule --> DatabaseService
  AppModule --> CommonModule
  CommonModule --> ConfigModule
  CommonModule --> ConfigHostModule
  CommonModule --> DatabaseService
  AppModule --> LocationsModule
  LocationsModule --> ConfigModule
  LocationsModule --> ConfigHostModule
  LocationsModule --> DatabaseService
  AppModule --> MailModule
  AppModule --> SmsModule
  AppModule --> ConfigHostModule
