graph LR
  AppModule --> ConfigModule
  ConfigModule --> ConfigHostModule
  ConfigHostModule --> ConfigModule
  ConfigHostModule --> PrismaModule
  PrismaModule --> ConfigModule
  PrismaModule --> ConfigHostModule
  ConfigModule --> PrismaModule
  AppModule --> PrismaModule
  AppModule --> AuthModule
  AuthModule --> JwtModule
  JwtModule --> ConfigModule
  JwtModule --> ConfigHostModule
  JwtModule --> PrismaModule
  AuthModule --> PrismaModule
  AuthModule --> RolesModule
  RolesModule --> PrismaModule
  RolesModule --> ConfigModule
  RolesModule --> ConfigHostModule
  AuthModule --> PermissionsModule
  PermissionsModule --> PrismaModule
  PermissionsModule --> ConfigModule
  PermissionsModule --> ConfigHostModule
  AuthModule --> MailModule
  MailModule --> ConfigModule
  MailModule --> ConfigHostModule
  MailModule --> PrismaModule
  AuthModule --> SmsModule
  SmsModule --> ConfigModule
  SmsModule --> ConfigHostModule
  SmsModule --> PrismaModule
  AuthModule --> ConfigModule
  AuthModule --> ConfigHostModule
  AppModule --> RolesModule
  AppModule --> UsersModule
  UsersModule --> ConfigModule
  UsersModule --> ConfigHostModule
  UsersModule --> PrismaModule
  AppModule --> TestingModule
  TestingModule --> ConfigModule
  TestingModule --> ConfigHostModule
  TestingModule --> PrismaModule
  AppModule --> CommonModule
  CommonModule --> ConfigModule
  CommonModule --> ConfigHostModule
  CommonModule --> PrismaModule
  AppModule --> LocationsModule
  LocationsModule --> ConfigModule
  LocationsModule --> ConfigHostModule
  LocationsModule --> PrismaModule
  AppModule --> MailModule
  AppModule --> SmsModule
  AppModule --> ConfigHostModule
